version: '2.1'

services:

  funding_contract_api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      RPC_HOST: 111.11.111.111
      RPC_PORT: 7545
      FUNDING_CONTRACT: "0x8c70b83edbab3455499344f5b9a25998c56fcd82"
      AUTH0_DOMAIN: "registree.eu.auth0.com"
      API_IDENTIFIER: "https://registree.rocks/apis"
      ALGORITHMS: "['RS256']"
    networks:
      - backbone

  nginx:
    restart: always
    build: ./nginx
    links:
      - funding_contract_api
    ports:
      - "2096:2096"
    volumes:
      - ~/cert:/etc/cert
    networks:
      - backbone
      
networks: 
  backbone:
    driver: bridge
